System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [],
    "stage": 0
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/dev/dependency-bundle.js": [
      "tide/components.js",
      "tide/utils.js",
      "npm:react-dom@0.14.8.js",
      "npm:react-dom@0.14.8/index.js",
      "npm:react@0.14.8/lib/ReactDOM.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.7.js",
      "npm:process@0.11.7/browser.js",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment.js",
      "npm:fbjs@0.6.1/lib/warning.js",
      "npm:fbjs@0.6.1/lib/emptyFunction.js",
      "npm:react@0.14.8/lib/renderSubtreeIntoContainer.js",
      "npm:react@0.14.8/lib/ReactMount.js",
      "npm:react@0.14.8/lib/validateDOMNesting.js",
      "npm:react@0.14.8/lib/Object.assign.js",
      "npm:react@0.14.8/lib/shouldUpdateReactComponent.js",
      "npm:react@0.14.8/lib/setInnerHTML.js",
      "npm:fbjs@0.6.1/lib/invariant.js",
      "npm:react@0.14.8/lib/instantiateReactComponent.js",
      "npm:react@0.14.8/lib/ReactNativeComponent.js",
      "npm:react@0.14.8/lib/ReactEmptyComponent.js",
      "npm:react@0.14.8/lib/ReactReconciler.js",
      "npm:react@0.14.8/lib/ReactRef.js",
      "npm:react@0.14.8/lib/ReactOwner.js",
      "npm:react@0.14.8/lib/ReactEmptyComponentRegistry.js",
      "npm:react@0.14.8/lib/ReactElement.js",
      "npm:react@0.14.8/lib/canDefineProperty.js",
      "npm:react@0.14.8/lib/ReactCurrentOwner.js",
      "npm:react@0.14.8/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.6.1/lib/emptyObject.js",
      "npm:react@0.14.8/lib/ReactUpdateQueue.js",
      "npm:react@0.14.8/lib/ReactUpdates.js",
      "npm:react@0.14.8/lib/Transaction.js",
      "npm:react@0.14.8/lib/ReactPerf.js",
      "npm:react@0.14.8/lib/PooledClass.js",
      "npm:react@0.14.8/lib/CallbackQueue.js",
      "npm:react@0.14.8/lib/ReactInstanceMap.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocationNames.js",
      "npm:react@0.14.8/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.6.1/lib/keyMirror.js",
      "npm:react@0.14.8/lib/ReactComponentEnvironment.js",
      "npm:fbjs@0.6.1/lib/containsNode.js",
      "npm:fbjs@0.6.1/lib/isTextNode.js",
      "npm:fbjs@0.6.1/lib/isNode.js",
      "npm:react@0.14.8/lib/ReactMarkupChecksum.js",
      "npm:react@0.14.8/lib/adler32.js",
      "npm:react@0.14.8/lib/ReactInstanceHandles.js",
      "npm:react@0.14.8/lib/ReactRootIndex.js",
      "npm:react@0.14.8/lib/ReactDOMFeatureFlags.js",
      "npm:react@0.14.8/lib/ReactBrowserEventEmitter.js",
      "npm:react@0.14.8/lib/isEventSupported.js",
      "npm:react@0.14.8/lib/ViewportMetrics.js",
      "npm:react@0.14.8/lib/ReactEventEmitterMixin.js",
      "npm:react@0.14.8/lib/EventPluginHub.js",
      "npm:react@0.14.8/lib/forEachAccumulated.js",
      "npm:react@0.14.8/lib/accumulateInto.js",
      "npm:react@0.14.8/lib/ReactErrorUtils.js",
      "npm:react@0.14.8/lib/EventPluginUtils.js",
      "npm:react@0.14.8/lib/EventConstants.js",
      "npm:react@0.14.8/lib/EventPluginRegistry.js",
      "npm:react@0.14.8/lib/DOMProperty.js",
      "npm:react@0.14.8/lib/findDOMNode.js",
      "npm:react@0.14.8/lib/ReactVersion.js",
      "npm:react@0.14.8/lib/ReactDefaultInjection.js",
      "npm:react@0.14.8/lib/ReactDefaultPerf.js",
      "npm:fbjs@0.6.1/lib/performanceNow.js",
      "npm:fbjs@0.6.1/lib/performance.js",
      "npm:react@0.14.8/lib/ReactDefaultPerfAnalysis.js",
      "npm:react@0.14.8/lib/SVGDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/SimpleEventPlugin.js",
      "npm:fbjs@0.6.1/lib/keyOf.js",
      "npm:react@0.14.8/lib/getEventCharCode.js",
      "npm:react@0.14.8/lib/SyntheticWheelEvent.js",
      "npm:react@0.14.8/lib/SyntheticMouseEvent.js",
      "npm:react@0.14.8/lib/getEventModifierState.js",
      "npm:react@0.14.8/lib/SyntheticUIEvent.js",
      "npm:react@0.14.8/lib/getEventTarget.js",
      "npm:react@0.14.8/lib/SyntheticEvent.js",
      "npm:react@0.14.8/lib/SyntheticTouchEvent.js",
      "npm:react@0.14.8/lib/SyntheticDragEvent.js",
      "npm:react@0.14.8/lib/SyntheticKeyboardEvent.js",
      "npm:react@0.14.8/lib/getEventKey.js",
      "npm:react@0.14.8/lib/SyntheticFocusEvent.js",
      "npm:react@0.14.8/lib/SyntheticClipboardEvent.js",
      "npm:react@0.14.8/lib/EventPropagators.js",
      "npm:fbjs@0.6.1/lib/EventListener.js",
      "npm:react@0.14.8/lib/ServerReactRootIndex.js",
      "npm:react@0.14.8/lib/SelectEventPlugin.js",
      "npm:fbjs@0.6.1/lib/shallowEqual.js",
      "npm:react@0.14.8/lib/isTextInputElement.js",
      "npm:fbjs@0.6.1/lib/getActiveElement.js",
      "npm:react@0.14.8/lib/ReactInputSelection.js",
      "npm:fbjs@0.6.1/lib/focusNode.js",
      "npm:react@0.14.8/lib/ReactDOMSelection.js",
      "npm:react@0.14.8/lib/getTextContentAccessor.js",
      "npm:react@0.14.8/lib/getNodeForCharacterOffset.js",
      "npm:react@0.14.8/lib/ReactReconcileTransaction.js",
      "npm:react@0.14.8/lib/ReactInjection.js",
      "npm:react@0.14.8/lib/ReactClass.js",
      "npm:react@0.14.8/lib/ReactNoopUpdateQueue.js",
      "npm:react@0.14.8/lib/ReactComponent.js",
      "npm:react@0.14.8/lib/ReactEventListener.js",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition.js",
      "npm:react@0.14.8/lib/ReactDOMTextComponent.js",
      "npm:react@0.14.8/lib/setTextContent.js",
      "npm:react@0.14.8/lib/escapeTextContentForBrowser.js",
      "npm:react@0.14.8/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@0.14.8/lib/ReactDOMIDOperations.js",
      "npm:react@0.14.8/lib/DOMPropertyOperations.js",
      "npm:react@0.14.8/lib/quoteAttributeValueForBrowser.js",
      "npm:react@0.14.8/lib/DOMChildrenOperations.js",
      "npm:react@0.14.8/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@0.14.8/lib/Danger.js",
      "npm:fbjs@0.6.1/lib/getMarkupWrap.js",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed.js",
      "npm:fbjs@0.6.1/lib/toArray.js",
      "npm:react@0.14.8/lib/ReactDOMComponent.js",
      "npm:react@0.14.8/lib/ReactMultiChild.js",
      "npm:react@0.14.8/lib/flattenChildren.js",
      "npm:react@0.14.8/lib/traverseAllChildren.js",
      "npm:react@0.14.8/lib/getIteratorFn.js",
      "npm:react@0.14.8/lib/ReactChildReconciler.js",
      "npm:react@0.14.8/lib/ReactDOMTextarea.js",
      "npm:react@0.14.8/lib/LinkedValueUtils.js",
      "npm:react@0.14.8/lib/ReactPropTypes.js",
      "npm:react@0.14.8/lib/ReactDOMSelect.js",
      "npm:react@0.14.8/lib/ReactDOMOption.js",
      "npm:react@0.14.8/lib/ReactChildren.js",
      "npm:react@0.14.8/lib/ReactDOMInput.js",
      "npm:react@0.14.8/lib/ReactDOMButton.js",
      "npm:react@0.14.8/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly.js",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName.js",
      "npm:fbjs@0.6.1/lib/hyphenate.js",
      "npm:react@0.14.8/lib/dangerousStyleValue.js",
      "npm:react@0.14.8/lib/CSSProperty.js",
      "npm:fbjs@0.6.1/lib/camelizeStyleName.js",
      "npm:fbjs@0.6.1/lib/camelize.js",
      "npm:react@0.14.8/lib/AutoFocusUtils.js",
      "npm:react@0.14.8/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@0.14.8/lib/ReactBrowserComponentMixin.js",
      "npm:react@0.14.8/lib/HTMLDOMPropertyConfig.js",
      "npm:react@0.14.8/lib/EnterLeaveEventPlugin.js",
      "npm:react@0.14.8/lib/DefaultEventPluginOrder.js",
      "npm:react@0.14.8/lib/ClientReactRootIndex.js",
      "npm:react@0.14.8/lib/ChangeEventPlugin.js",
      "npm:react@0.14.8/lib/BeforeInputEventPlugin.js",
      "npm:react@0.14.8/lib/SyntheticInputEvent.js",
      "npm:react@0.14.8/lib/SyntheticCompositionEvent.js",
      "npm:react@0.14.8/lib/FallbackCompositionState.js",
      "npm:react@0.14.8.js",
      "npm:react@0.14.8/react.js",
      "npm:react@0.14.8/lib/React.js",
      "npm:react@0.14.8/lib/deprecated.js",
      "npm:react@0.14.8/lib/ReactIsomorphic.js",
      "npm:react@0.14.8/lib/onlyChild.js",
      "npm:react@0.14.8/lib/ReactElementValidator.js",
      "npm:react@0.14.8/lib/ReactDOMFactories.js",
      "npm:fbjs@0.6.1/lib/mapObject.js",
      "npm:react@0.14.8/lib/ReactDOMServer.js",
      "npm:react@0.14.8/lib/ReactServerRendering.js",
      "npm:react@0.14.8/lib/ReactServerRenderingTransaction.js",
      "npm:react@0.14.8/lib/ReactServerBatchingStrategy.js",
      "npm:mobx-react@3.5.3.js",
      "npm:mobx-react@3.5.3/index.js",
      "npm:mobx@2.4.1.js",
      "npm:mobx@2.4.1/lib/mobx.js",
      "npm:react-router@2.6.1.js",
      "npm:react-router@2.6.1/lib/index.js",
      "npm:react-router@2.6.1/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createHistory.js",
      "npm:history@2.1.2/lib/deprecate.js",
      "npm:warning@2.1.0.js",
      "npm:warning@2.1.0/browser.js",
      "npm:history@2.1.2/lib/runTransitionHook.js",
      "npm:history@2.1.2/lib/createLocation.js",
      "npm:history@2.1.2/lib/PathUtils.js",
      "npm:history@2.1.2/lib/Actions.js",
      "npm:history@2.1.2/lib/AsyncUtils.js",
      "npm:deep-equal@1.0.1.js",
      "npm:deep-equal@1.0.1/index.js",
      "npm:deep-equal@1.0.1/lib/is_arguments.js",
      "npm:deep-equal@1.0.1/lib/keys.js",
      "npm:invariant@2.2.1.js",
      "npm:invariant@2.2.1/browser.js",
      "npm:history@2.1.2/lib/useBasename.js",
      "npm:history@2.1.2/lib/ExecutionEnvironment.js",
      "npm:history@2.1.2/lib/useQueries.js",
      "npm:query-string@3.0.3.js",
      "npm:query-string@3.0.3/index.js",
      "npm:strict-uri-encode@1.1.0.js",
      "npm:strict-uri-encode@1.1.0/index.js",
      "npm:react-router@2.6.1/lib/hashHistory.js",
      "npm:react-router@2.6.1/lib/createRouterHistory.js",
      "npm:react-router@2.6.1/lib/useRouterHistory.js",
      "npm:history@2.1.2/lib/createHashHistory.js",
      "npm:history@2.1.2/lib/createDOMHistory.js",
      "npm:history@2.1.2/lib/DOMUtils.js",
      "npm:history@2.1.2/lib/DOMStateStorage.js",
      "npm:react-router@2.6.1/lib/browserHistory.js",
      "npm:history@2.1.2/lib/createBrowserHistory.js",
      "npm:react-router@2.6.1/lib/applyRouterMiddleware.js",
      "npm:react-router@2.6.1/lib/RouterContext.js",
      "npm:react-router@2.6.1/lib/routerWarning.js",
      "npm:warning@3.0.0.js",
      "npm:warning@3.0.0/browser.js",
      "npm:react-router@2.6.1/lib/RouteUtils.js",
      "npm:react-router@2.6.1/lib/getRouteParams.js",
      "npm:react-router@2.6.1/lib/PatternUtils.js",
      "npm:react-router@2.6.1/lib/deprecateObjectProperties.js",
      "npm:react-router@2.6.1/lib/match.js",
      "npm:react-router@2.6.1/lib/RouterUtils.js",
      "npm:react-router@2.6.1/lib/createTransitionManager.js",
      "npm:react-router@2.6.1/lib/matchRoutes.js",
      "npm:react-router@2.6.1/lib/makeStateWithLocation.js",
      "npm:react-router@2.6.1/lib/AsyncUtils.js",
      "npm:react-router@2.6.1/lib/getComponents.js",
      "npm:react-router@2.6.1/lib/isActive.js",
      "npm:react-router@2.6.1/lib/TransitionUtils.js",
      "npm:react-router@2.6.1/lib/computeChangedRoutes.js",
      "npm:react-router@2.6.1/lib/RoutingContext.js",
      "npm:react-router@2.6.1/lib/useRoutes.js",
      "npm:react-router@2.6.1/lib/RouteContext.js",
      "npm:react-router@2.6.1/lib/Lifecycle.js",
      "npm:react-router@2.6.1/lib/History.js",
      "npm:react-router@2.6.1/lib/InternalPropTypes.js",
      "npm:react-router@2.6.1/lib/Route.js",
      "npm:react-router@2.6.1/lib/Redirect.js",
      "npm:react-router@2.6.1/lib/IndexRoute.js",
      "npm:react-router@2.6.1/lib/IndexRedirect.js",
      "npm:react-router@2.6.1/lib/withRouter.js",
      "npm:react-router@2.6.1/lib/PropTypes.js",
      "npm:hoist-non-react-statics@1.2.0.js",
      "npm:hoist-non-react-statics@1.2.0/index.js",
      "npm:react-router@2.6.1/lib/IndexLink.js",
      "npm:react-router@2.6.1/lib/Link.js",
      "npm:react-router@2.6.1/lib/Router.js",
      "npm:classnames@2.2.5/bind.js",
      "npm:babel-preset-es2015@6.9.0.js",
      "npm:babel-preset-es2015@6.9.0/index.js",
      "npm:babel-plugin-transform-regenerator@6.9.0.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/index.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/visit.js",
      "npm:private@0.1.6.js",
      "npm:private@0.1.6/private.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/util.js",
      "npm:babel-types@6.11.1.js",
      "npm:babel-types@6.11.1/lib/index.js",
      "npm:babel-traverse@6.10.4.js",
      "npm:babel-traverse@6.10.4/lib/index.js",
      "npm:babel-traverse@6.10.4/lib/cache.js",
      "npm:babel-runtime@6.9.2/core-js/weak-map.js",
      "npm:core-js@2.4.1/library/fn/weak-map.js",
      "npm:core-js@2.4.1/library/modules/_core.js",
      "npm:core-js@2.4.1/library/modules/es6.weak-map.js",
      "npm:core-js@2.4.1/library/modules/_collection.js",
      "npm:core-js@2.4.1/library/modules/_descriptors.js",
      "npm:core-js@2.4.1/library/modules/_fails.js",
      "npm:core-js@2.4.1/library/modules/_array-methods.js",
      "npm:core-js@2.4.1/library/modules/_array-species-create.js",
      "npm:core-js@2.4.1/library/modules/_array-species-constructor.js",
      "npm:core-js@2.4.1/library/modules/_wks.js",
      "npm:core-js@2.4.1/library/modules/_global.js",
      "npm:core-js@2.4.1/library/modules/_uid.js",
      "npm:core-js@2.4.1/library/modules/_shared.js",
      "npm:core-js@2.4.1/library/modules/_is-array.js",
      "npm:core-js@2.4.1/library/modules/_cof.js",
      "npm:core-js@2.4.1/library/modules/_is-object.js",
      "npm:core-js@2.4.1/library/modules/_to-length.js",
      "npm:core-js@2.4.1/library/modules/_to-integer.js",
      "npm:core-js@2.4.1/library/modules/_to-object.js",
      "npm:core-js@2.4.1/library/modules/_defined.js",
      "npm:core-js@2.4.1/library/modules/_iobject.js",
      "npm:core-js@2.4.1/library/modules/_ctx.js",
      "npm:core-js@2.4.1/library/modules/_a-function.js",
      "npm:core-js@2.4.1/library/modules/_object-dp.js",
      "npm:core-js@2.4.1/library/modules/_to-primitive.js",
      "npm:core-js@2.4.1/library/modules/_ie8-dom-define.js",
      "npm:core-js@2.4.1/library/modules/_dom-create.js",
      "npm:core-js@2.4.1/library/modules/_an-object.js",
      "npm:core-js@2.4.1/library/modules/_set-to-string-tag.js",
      "npm:core-js@2.4.1/library/modules/_has.js",
      "npm:core-js@2.4.1/library/modules/_an-instance.js",
      "npm:core-js@2.4.1/library/modules/_for-of.js",
      "npm:core-js@2.4.1/library/modules/core.get-iterator-method.js",
      "npm:core-js@2.4.1/library/modules/_iterators.js",
      "npm:core-js@2.4.1/library/modules/_classof.js",
      "npm:core-js@2.4.1/library/modules/_is-array-iter.js",
      "npm:core-js@2.4.1/library/modules/_iter-call.js",
      "npm:core-js@2.4.1/library/modules/_redefine-all.js",
      "npm:core-js@2.4.1/library/modules/_hide.js",
      "npm:core-js@2.4.1/library/modules/_property-desc.js",
      "npm:core-js@2.4.1/library/modules/_meta.js",
      "npm:core-js@2.4.1/library/modules/_export.js",
      "npm:core-js@2.4.1/library/modules/_collection-weak.js",
      "npm:core-js@2.4.1/library/modules/_object-assign.js",
      "npm:core-js@2.4.1/library/modules/_object-pie.js",
      "npm:core-js@2.4.1/library/modules/_object-gops.js",
      "npm:core-js@2.4.1/library/modules/_object-keys.js",
      "npm:core-js@2.4.1/library/modules/_enum-bug-keys.js",
      "npm:core-js@2.4.1/library/modules/_object-keys-internal.js",
      "npm:core-js@2.4.1/library/modules/_shared-key.js",
      "npm:core-js@2.4.1/library/modules/_array-includes.js",
      "npm:core-js@2.4.1/library/modules/_to-index.js",
      "npm:core-js@2.4.1/library/modules/_to-iobject.js",
      "npm:core-js@2.4.1/library/modules/_redefine.js",
      "npm:core-js@2.4.1/library/modules/web.dom.iterable.js",
      "npm:core-js@2.4.1/library/modules/es6.array.iterator.js",
      "npm:core-js@2.4.1/library/modules/_iter-define.js",
      "npm:core-js@2.4.1/library/modules/_object-gpo.js",
      "npm:core-js@2.4.1/library/modules/_iter-create.js",
      "npm:core-js@2.4.1/library/modules/_object-create.js",
      "npm:core-js@2.4.1/library/modules/_html.js",
      "npm:core-js@2.4.1/library/modules/_object-dps.js",
      "npm:core-js@2.4.1/library/modules/_library.js",
      "npm:core-js@2.4.1/library/modules/_iter-step.js",
      "npm:core-js@2.4.1/library/modules/_add-to-unscopables.js",
      "npm:core-js@2.4.1/library/modules/es6.object.to-string.js",
      "npm:lodash@4.13.1/includes.js",
      "npm:lodash@4.13.1/values.js",
      "npm:lodash@4.13.1/keys.js",
      "npm:lodash@4.13.1/_isPrototype.js",
      "npm:lodash@4.13.1/_isIndex.js",
      "npm:lodash@4.13.1/isArrayLike.js",
      "npm:lodash@4.13.1/isLength.js",
      "npm:lodash@4.13.1/isFunction.js",
      "npm:lodash@4.13.1/isObject.js",
      "npm:lodash@4.13.1/_getLength.js",
      "npm:lodash@4.13.1/_baseProperty.js",
      "npm:lodash@4.13.1/_indexKeys.js",
      "npm:lodash@4.13.1/isString.js",
      "npm:lodash@4.13.1/isObjectLike.js",
      "npm:lodash@4.13.1/isArray.js",
      "npm:lodash@4.13.1/isArguments.js",
      "npm:lodash@4.13.1/isArrayLikeObject.js",
      "npm:lodash@4.13.1/_baseTimes.js",
      "npm:lodash@4.13.1/_baseKeys.js",
      "npm:lodash@4.13.1/_baseHas.js",
      "npm:lodash@4.13.1/_getPrototype.js",
      "npm:lodash@4.13.1/_baseValues.js",
      "npm:lodash@4.13.1/_arrayMap.js",
      "npm:lodash@4.13.1/toInteger.js",
      "npm:lodash@4.13.1/toFinite.js",
      "npm:lodash@4.13.1/toNumber.js",
      "npm:lodash@4.13.1/isSymbol.js",
      "npm:lodash@4.13.1/_baseIndexOf.js",
      "npm:lodash@4.13.1/_indexOfNaN.js",
      "npm:babel-messages@6.8.0.js",
      "npm:babel-messages@6.8.0/lib/index.js",
      "github:jspm/nodelibs-util@0.1.0.js",
      "github:jspm/nodelibs-util@0.1.0/index.js",
      "npm:util@0.10.3.js",
      "npm:util@0.10.3/util.js",
      "npm:inherits@2.0.1.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "npm:util@0.10.3/support/isBufferBrowser.js",
      "npm:babel-runtime@6.9.2/core-js/json/stringify.js",
      "npm:core-js@2.4.1/library/fn/json/stringify.js",
      "npm:babel-traverse@6.10.4/lib/visitors.js",
      "npm:lodash@4.13.1/clone.js",
      "npm:lodash@4.13.1/_baseClone.js",
      "npm:lodash@4.13.1/_isHostObject.js",
      "npm:lodash@4.13.1/isBuffer.js",
      "npm:lodash@4.13.1/stubFalse.js",
      "npm:lodash@4.13.1/_root.js",
      "npm:lodash@4.13.1/_checkGlobal.js",
      "npm:lodash@4.13.1/_initCloneObject.js",
      "npm:lodash@4.13.1/_baseCreate.js",
      "npm:lodash@4.13.1/_initCloneByTag.js",
      "npm:lodash@4.13.1/_cloneTypedArray.js",
      "npm:lodash@4.13.1/_cloneArrayBuffer.js",
      "npm:lodash@4.13.1/_Uint8Array.js",
      "npm:lodash@4.13.1/_cloneSymbol.js",
      "npm:lodash@4.13.1/_Symbol.js",
      "npm:lodash@4.13.1/_cloneSet.js",
      "npm:lodash@4.13.1/_setToArray.js",
      "npm:lodash@4.13.1/_arrayReduce.js",
      "npm:lodash@4.13.1/_addSetEntry.js",
      "npm:lodash@4.13.1/_cloneRegExp.js",
      "npm:lodash@4.13.1/_cloneMap.js",
      "npm:lodash@4.13.1/_mapToArray.js",
      "npm:lodash@4.13.1/_addMapEntry.js",
      "npm:lodash@4.13.1/_cloneDataView.js",
      "npm:lodash@4.13.1/_initCloneArray.js",
      "npm:lodash@4.13.1/_getTag.js",
      "npm:lodash@4.13.1/_toSource.js",
      "npm:lodash@4.13.1/_WeakMap.js",
      "npm:lodash@4.13.1/_getNative.js",
      "npm:lodash@4.13.1/_getValue.js",
      "npm:lodash@4.13.1/_baseIsNative.js",
      "npm:lodash@4.13.1/_isMasked.js",
      "npm:lodash@4.13.1/_coreJsData.js",
      "npm:lodash@4.13.1/_Set.js",
      "npm:lodash@4.13.1/_Promise.js",
      "npm:lodash@4.13.1/_Map.js",
      "npm:lodash@4.13.1/_DataView.js",
      "npm:lodash@4.13.1/_getAllKeys.js",
      "npm:lodash@4.13.1/_getSymbols.js",
      "npm:lodash@4.13.1/stubArray.js",
      "npm:lodash@4.13.1/_baseGetAllKeys.js",
      "npm:lodash@4.13.1/_arrayPush.js",
      "npm:lodash@4.13.1/_copySymbols.js",
      "npm:lodash@4.13.1/_copyObject.js",
      "npm:lodash@4.13.1/_assignValue.js",
      "npm:lodash@4.13.1/eq.js",
      "npm:lodash@4.13.1/_copyArray.js",
      "npm:lodash@4.13.1/_cloneBuffer.js",
      "npm:lodash@4.13.1/_baseAssign.js",
      "npm:lodash@4.13.1/_arrayEach.js",
      "npm:lodash@4.13.1/_Stack.js",
      "npm:lodash@4.13.1/_stackSet.js",
      "npm:lodash@4.13.1/_MapCache.js",
      "npm:lodash@4.13.1/_mapCacheSet.js",
      "npm:lodash@4.13.1/_getMapData.js",
      "npm:lodash@4.13.1/_isKeyable.js",
      "npm:lodash@4.13.1/_mapCacheHas.js",
      "npm:lodash@4.13.1/_mapCacheGet.js",
      "npm:lodash@4.13.1/_mapCacheDelete.js",
      "npm:lodash@4.13.1/_mapCacheClear.js",
      "npm:lodash@4.13.1/_ListCache.js",
      "npm:lodash@4.13.1/_listCacheSet.js",
      "npm:lodash@4.13.1/_assocIndexOf.js",
      "npm:lodash@4.13.1/_listCacheHas.js",
      "npm:lodash@4.13.1/_listCacheGet.js",
      "npm:lodash@4.13.1/_listCacheDelete.js",
      "npm:lodash@4.13.1/_listCacheClear.js",
      "npm:lodash@4.13.1/_Hash.js",
      "npm:lodash@4.13.1/_hashSet.js",
      "npm:lodash@4.13.1/_nativeCreate.js",
      "npm:lodash@4.13.1/_hashHas.js",
      "npm:lodash@4.13.1/_hashGet.js",
      "npm:lodash@4.13.1/_hashDelete.js",
      "npm:lodash@4.13.1/_hashClear.js",
      "npm:lodash@4.13.1/_stackHas.js",
      "npm:lodash@4.13.1/_stackGet.js",
      "npm:lodash@4.13.1/_stackDelete.js",
      "npm:lodash@4.13.1/_stackClear.js",
      "npm:babel-traverse@6.10.4/lib/path/lib/virtual-types.js",
      "npm:babel-runtime@6.9.2/core-js/get-iterator.js",
      "npm:core-js@2.4.1/library/fn/get-iterator.js",
      "npm:core-js@2.4.1/library/modules/core.get-iterator.js",
      "npm:core-js@2.4.1/library/modules/es6.string.iterator.js",
      "npm:core-js@2.4.1/library/modules/_string-at.js",
      "npm:babel-runtime@6.9.2/core-js/object/keys.js",
      "npm:core-js@2.4.1/library/fn/object/keys.js",
      "npm:core-js@2.4.1/library/modules/es6.object.keys.js",
      "npm:core-js@2.4.1/library/modules/_object-sap.js",
      "npm:babel-runtime@6.9.2/helpers/typeof.js",
      "npm:babel-runtime@6.9.2/core-js/symbol.js",
      "npm:core-js@2.4.1/library/fn/symbol.js",
      "npm:core-js@2.4.1/library/fn/symbol/index.js",
      "npm:core-js@2.4.1/library/modules/es7.symbol.observable.js",
      "npm:core-js@2.4.1/library/modules/_wks-define.js",
      "npm:core-js@2.4.1/library/modules/_wks-ext.js",
      "npm:core-js@2.4.1/library/modules/es7.symbol.async-iterator.js",
      "npm:core-js@2.4.1/library/modules/es6.symbol.js",
      "npm:core-js@2.4.1/library/modules/_object-gopn.js",
      "npm:core-js@2.4.1/library/modules/_object-gopd.js",
      "npm:core-js@2.4.1/library/modules/_object-gopn-ext.js",
      "npm:core-js@2.4.1/library/modules/_enum-keys.js",
      "npm:core-js@2.4.1/library/modules/_keyof.js",
      "npm:babel-runtime@6.9.2/core-js/symbol/iterator.js",
      "npm:core-js@2.4.1/library/fn/symbol/iterator.js",
      "npm:babel-traverse@6.10.4/lib/context.js",
      "npm:babel-traverse@6.10.4/lib/path/index.js",
      "npm:babel-traverse@6.10.4/lib/path/comments.js",
      "npm:babel-traverse@6.10.4/lib/path/family.js",
      "npm:babel-traverse@6.10.4/lib/path/modification.js",
      "npm:babel-traverse@6.10.4/lib/path/lib/hoister.js",
      "npm:babel-runtime@6.9.2/helpers/classCallCheck.js",
      "npm:babel-traverse@6.10.4/lib/path/removal.js",
      "npm:babel-traverse@6.10.4/lib/path/lib/removal-hooks.js",
      "npm:babel-traverse@6.10.4/lib/path/context.js",
      "npm:babel-traverse@6.10.4/lib/path/introspection.js",
      "npm:babel-traverse@6.10.4/lib/path/conversion.js",
      "npm:babel-traverse@6.10.4/lib/path/evaluation.js",
      "npm:babel-runtime@6.9.2/core-js/map.js",
      "npm:core-js@2.4.1/library/fn/map.js",
      "npm:core-js@2.4.1/library/modules/es7.map.to-json.js",
      "npm:core-js@2.4.1/library/modules/_collection-to-json.js",
      "npm:core-js@2.4.1/library/modules/_array-from-iterable.js",
      "npm:core-js@2.4.1/library/modules/es6.map.js",
      "npm:core-js@2.4.1/library/modules/_collection-strong.js",
      "npm:core-js@2.4.1/library/modules/_set-species.js",
      "npm:babel-traverse@6.10.4/lib/path/replacement.js",
      "npm:babylon@6.8.4.js",
      "npm:babylon@6.8.4/lib/index.js",
      "npm:babylon@6.8.4/lib/plugins/jsx/index.js",
      "npm:babylon@6.8.4/lib/util/whitespace.js",
      "npm:babylon@6.8.4/lib/util/identifier.js",
      "npm:babylon@6.8.4/lib/parser/index.js",
      "npm:babylon@6.8.4/lib/tokenizer/index.js",
      "npm:babylon@6.8.4/lib/tokenizer/state.js",
      "npm:babylon@6.8.4/lib/tokenizer/types.js",
      "npm:babylon@6.8.4/lib/tokenizer/context.js",
      "npm:babylon@6.8.4/lib/util/location.js",
      "npm:babel-runtime@6.9.2/helpers/createClass.js",
      "npm:babel-runtime@6.9.2/core-js/object/define-property.js",
      "npm:core-js@2.4.1/library/fn/object/define-property.js",
      "npm:core-js@2.4.1/library/modules/es6.object.define-property.js",
      "npm:babylon@6.8.4/lib/options.js",
      "npm:babel-runtime@6.9.2/helpers/inherits.js",
      "npm:babel-runtime@6.9.2/core-js/object/create.js",
      "npm:core-js@2.4.1/library/fn/object/create.js",
      "npm:core-js@2.4.1/library/modules/es6.object.create.js",
      "npm:babel-runtime@6.9.2/core-js/object/set-prototype-of.js",
      "npm:core-js@2.4.1/library/fn/object/set-prototype-of.js",
      "npm:core-js@2.4.1/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.4.1/library/modules/_set-proto.js",
      "npm:babel-runtime@6.9.2/helpers/possibleConstructorReturn.js",
      "npm:babel-runtime@6.9.2/core-js/object/get-prototype-of.js",
      "npm:core-js@2.4.1/library/fn/object/get-prototype-of.js",
      "npm:core-js@2.4.1/library/modules/es6.object.get-prototype-of.js",
      "npm:babylon@6.8.4/lib/plugins/jsx/xhtml.js",
      "npm:babylon@6.8.4/lib/plugins/flow.js",
      "npm:babylon@6.8.4/lib/parser/comments.js",
      "npm:babylon@6.8.4/lib/parser/location.js",
      "npm:babylon@6.8.4/lib/parser/node.js",
      "npm:babylon@6.8.4/lib/parser/expression.js",
      "npm:babylon@6.8.4/lib/parser/lval.js",
      "npm:babylon@6.8.4/lib/parser/statement.js",
      "npm:babylon@6.8.4/lib/parser/util.js",
      "npm:babel-code-frame@6.11.0.js",
      "npm:babel-code-frame@6.11.0/lib/index.js",
      "npm:chalk@1.1.3.js",
      "npm:chalk@1.1.3/index.js",
      "npm:supports-color@2.0.0.js",
      "npm:supports-color@2.0.0/index.js",
      "npm:has-ansi@2.0.0.js",
      "npm:has-ansi@2.0.0/index.js",
      "npm:ansi-regex@2.0.0.js",
      "npm:ansi-regex@2.0.0/index.js",
      "npm:strip-ansi@3.0.1.js",
      "npm:strip-ansi@3.0.1/index.js",
      "npm:ansi-styles@2.2.1.js",
      "npm:ansi-styles@2.2.1/index.js",
      "npm:escape-string-regexp@1.0.5.js",
      "npm:escape-string-regexp@1.0.5/index.js",
      "npm:esutils@2.0.2.js",
      "npm:esutils@2.0.2/lib/utils.js",
      "npm:esutils@2.0.2/lib/keyword.js",
      "npm:esutils@2.0.2/lib/code.js",
      "npm:esutils@2.0.2/lib/ast.js",
      "npm:js-tokens@2.0.0.js",
      "npm:js-tokens@2.0.0/index.js",
      "npm:babel-traverse@6.10.4/lib/path/inference/index.js",
      "npm:babel-traverse@6.10.4/lib/path/inference/inferers.js",
      "npm:babel-traverse@6.10.4/lib/path/inference/inferer-reference.js",
      "npm:babel-traverse@6.10.4/lib/path/ancestry.js",
      "npm:babel-traverse@6.10.4/lib/scope/index.js",
      "npm:globals@8.18.0.js",
      "npm:globals@8.18.0/index.js",
      "npm:globals@8.18.0/globals.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:babel-traverse@6.10.4/lib/scope/binding.js",
      "npm:lodash@4.13.1/defaults.js",
      "npm:lodash@4.13.1/rest.js",
      "npm:lodash@4.13.1/_apply.js",
      "npm:lodash@4.13.1/assignInWith.js",
      "npm:lodash@4.13.1/keysIn.js",
      "npm:lodash@4.13.1/_baseKeysIn.js",
      "npm:lodash@4.13.1/_iteratorToArray.js",
      "npm:lodash@4.13.1/_Reflect.js",
      "npm:lodash@4.13.1/_createAssigner.js",
      "npm:lodash@4.13.1/_isIterateeCall.js",
      "npm:lodash@4.13.1/_assignInDefaults.js",
      "npm:babel-traverse@6.10.4/lib/scope/lib/renamer.js",
      "npm:lodash@4.13.1/repeat.js",
      "npm:lodash@4.13.1/toString.js",
      "npm:lodash@4.13.1/_baseToString.js",
      "npm:lodash@4.13.1/_baseRepeat.js",
      "npm:lodash@4.13.1/assign.js",
      "npm:debug@2.2.0.js",
      "npm:debug@2.2.0/browser.js",
      "npm:debug@2.2.0/debug.js",
      "npm:ms@0.7.1.js",
      "npm:ms@0.7.1/index.js",
      "npm:babel-traverse@6.10.4/lib/hub.js",
      "npm:babel-runtime@6.9.2/core-js/object/get-own-property-symbols.js",
      "npm:core-js@2.4.1/library/fn/object/get-own-property-symbols.js",
      "npm:babel-types@6.11.1/lib/react.js",
      "npm:babel-types@6.11.1/lib/definitions/index.js",
      "npm:babel-types@6.11.1/lib/definitions/init.js",
      "npm:babel-types@6.11.1/lib/definitions/experimental.js",
      "npm:babel-types@6.11.1/lib/definitions/misc.js",
      "npm:babel-types@6.11.1/lib/definitions/jsx.js",
      "npm:babel-types@6.11.1/lib/definitions/flow.js",
      "npm:babel-types@6.11.1/lib/definitions/es2015.js",
      "npm:babel-types@6.11.1/lib/definitions/core.js",
      "npm:babel-types@6.11.1/lib/constants.js",
      "npm:babel-runtime@6.9.2/core-js/symbol/for.js",
      "npm:core-js@2.4.1/library/fn/symbol/for.js",
      "npm:lodash@4.13.1/uniq.js",
      "npm:lodash@4.13.1/_baseUniq.js",
      "npm:lodash@4.13.1/_createSet.js",
      "npm:lodash@4.13.1/noop.js",
      "npm:lodash@4.13.1/_cacheHas.js",
      "npm:lodash@4.13.1/_arrayIncludesWith.js",
      "npm:lodash@4.13.1/_arrayIncludes.js",
      "npm:lodash@4.13.1/_SetCache.js",
      "npm:lodash@4.13.1/_setCacheHas.js",
      "npm:lodash@4.13.1/_setCacheAdd.js",
      "npm:lodash@4.13.1/each.js",
      "npm:lodash@4.13.1/forEach.js",
      "npm:lodash@4.13.1/_baseIteratee.js",
      "npm:lodash@4.13.1/property.js",
      "npm:lodash@4.13.1/_toKey.js",
      "npm:lodash@4.13.1/_isKey.js",
      "npm:lodash@4.13.1/_basePropertyDeep.js",
      "npm:lodash@4.13.1/_baseGet.js",
      "npm:lodash@4.13.1/_castPath.js",
      "npm:lodash@4.13.1/_stringToPath.js",
      "npm:lodash@4.13.1/memoize.js",
      "npm:lodash@4.13.1/identity.js",
      "npm:lodash@4.13.1/_baseMatchesProperty.js",
      "npm:lodash@4.13.1/_matchesStrictComparable.js",
      "npm:lodash@4.13.1/_isStrictComparable.js",
      "npm:lodash@4.13.1/hasIn.js",
      "npm:lodash@4.13.1/_hasPath.js",
      "npm:lodash@4.13.1/_baseHasIn.js",
      "npm:lodash@4.13.1/get.js",
      "npm:lodash@4.13.1/_baseIsEqual.js",
      "npm:lodash@4.13.1/_baseIsEqualDeep.js",
      "npm:lodash@4.13.1/isTypedArray.js",
      "npm:lodash@4.13.1/_equalObjects.js",
      "npm:lodash@4.13.1/_equalByTag.js",
      "npm:lodash@4.13.1/_equalArrays.js",
      "npm:lodash@4.13.1/_arraySome.js",
      "npm:lodash@4.13.1/_baseMatches.js",
      "npm:lodash@4.13.1/_getMatchData.js",
      "npm:lodash@4.13.1/_baseIsMatch.js",
      "npm:lodash@4.13.1/_baseEach.js",
      "npm:lodash@4.13.1/_createBaseEach.js",
      "npm:lodash@4.13.1/_baseForOwn.js",
      "npm:lodash@4.13.1/_baseFor.js",
      "npm:lodash@4.13.1/_createBaseFor.js",
      "npm:lodash@4.13.1/compact.js",
      "npm:to-fast-properties@1.0.2.js",
      "npm:to-fast-properties@1.0.2/index.js",
      "npm:babel-types@6.11.1/lib/flow.js",
      "npm:babel-types@6.11.1/lib/converters.js",
      "npm:lodash@4.13.1/isRegExp.js",
      "npm:lodash@4.13.1/isNumber.js",
      "npm:lodash@4.13.1/isPlainObject.js",
      "npm:babel-runtime@6.9.2/core-js/number/max-safe-integer.js",
      "npm:core-js@2.4.1/library/fn/number/max-safe-integer.js",
      "npm:core-js@2.4.1/library/modules/es6.number.max-safe-integer.js",
      "npm:babel-types@6.11.1/lib/validators.js",
      "npm:babel-types@6.11.1/lib/retrievers.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/emit.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/meta.js",
      "github:jspm/nodelibs-assert@0.1.0.js",
      "github:jspm/nodelibs-assert@0.1.0/index.js",
      "npm:assert@1.4.1.js",
      "npm:assert@1.4.1/assert.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/leap.js",
      "npm:babel-plugin-transform-regenerator@6.9.0/lib/hoist.js",
      "npm:babel-plugin-transform-es2015-modules-commonjs@6.10.3.js",
      "npm:babel-plugin-transform-es2015-modules-commonjs@6.10.3/lib/index.js",
      "npm:babel-template@6.9.0.js",
      "npm:babel-template@6.9.0/lib/index.js",
      "npm:lodash@4.13.1/has.js",
      "npm:lodash@4.13.1/cloneDeep.js",
      "github:jspm/nodelibs-path@0.1.0.js",
      "github:jspm/nodelibs-path@0.1.0/index.js",
      "npm:path-browserify@0.0.0.js",
      "npm:path-browserify@0.0.0/index.js",
      "npm:babel-plugin-transform-strict-mode@6.11.3.js",
      "npm:babel-plugin-transform-strict-mode@6.11.3/lib/index.js",
      "npm:babel-plugin-transform-es2015-typeof-symbol@6.8.0.js",
      "npm:babel-plugin-transform-es2015-typeof-symbol@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.10.1.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.10.1/lib/index.js",
      "npm:lodash@4.13.1/extend.js",
      "npm:lodash@4.13.1/assignIn.js",
      "npm:babel-plugin-transform-es2015-block-scoping@6.10.1/lib/tdz.js",
      "npm:babel-plugin-transform-es2015-destructuring@6.9.0.js",
      "npm:babel-plugin-transform-es2015-destructuring@6.9.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-parameters@6.11.3.js",
      "npm:babel-plugin-transform-es2015-parameters@6.11.3/lib/index.js",
      "npm:babel-plugin-transform-es2015-parameters@6.11.3/lib/rest.js",
      "npm:babel-plugin-transform-es2015-parameters@6.11.3/lib/default.js",
      "npm:babel-helper-call-delegate@6.8.0.js",
      "npm:babel-helper-call-delegate@6.8.0/lib/index.js",
      "npm:babel-helper-hoist-variables@6.8.0.js",
      "npm:babel-helper-hoist-variables@6.8.0/lib/index.js",
      "npm:babel-helper-get-function-arity@6.8.0.js",
      "npm:babel-helper-get-function-arity@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-parameters@6.11.3/lib/destructuring.js",
      "npm:babel-plugin-transform-es2015-spread@6.8.0.js",
      "npm:babel-plugin-transform-es2015-spread@6.8.0/lib/index.js",
      "npm:babel-plugin-check-es2015-constants@6.8.0.js",
      "npm:babel-plugin-check-es2015-constants@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-unicode-regex@6.11.0.js",
      "npm:babel-plugin-transform-es2015-unicode-regex@6.11.0/lib/index.js",
      "npm:babel-helper-regex@6.9.0.js",
      "npm:babel-helper-regex@6.9.0/lib/index.js",
      "npm:lodash@4.13.1/pull.js",
      "npm:lodash@4.13.1/pullAll.js",
      "npm:lodash@4.13.1/_basePullAll.js",
      "npm:lodash@4.13.1/_baseUnary.js",
      "npm:lodash@4.13.1/_baseIndexOfWith.js",
      "npm:regexpu-core@2.0.0.js",
      "npm:regexpu-core@2.0.0/rewrite-pattern.js",
      "npm:regexpu-core@2.0.0/data/character-class-escape-sets.js",
      "npm:regenerate@1.3.1.js",
      "npm:regenerate@1.3.1/regenerate.js",
      "npm:regexpu-core@2.0.0/data/iu-mappings.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:regjsparser@0.1.5.js",
      "npm:regjsparser@0.1.5/parser.js",
      "npm:regjsgen@0.2.0.js",
      "npm:regjsgen@0.2.0/regjsgen.js",
      "npm:babel-plugin-transform-es2015-sticky-regex@6.8.0.js",
      "npm:babel-plugin-transform-es2015-sticky-regex@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-for-of@6.8.0.js",
      "npm:babel-plugin-transform-es2015-for-of@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-computed-properties@6.8.0.js",
      "npm:babel-plugin-transform-es2015-computed-properties@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-duplicate-keys@6.8.0.js",
      "npm:babel-plugin-transform-es2015-duplicate-keys@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-shorthand-properties@6.8.0.js",
      "npm:babel-plugin-transform-es2015-shorthand-properties@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-object-super@6.8.0.js",
      "npm:babel-plugin-transform-es2015-object-super@6.8.0/lib/index.js",
      "npm:babel-helper-replace-supers@6.8.0.js",
      "npm:babel-helper-replace-supers@6.8.0/lib/index.js",
      "npm:babel-helper-optimise-call-expression@6.8.0.js",
      "npm:babel-helper-optimise-call-expression@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-classes@6.9.0.js",
      "npm:babel-plugin-transform-es2015-classes@6.9.0/lib/index.js",
      "npm:babel-helper-function-name@6.8.0.js",
      "npm:babel-helper-function-name@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-classes@6.9.0/lib/vanilla.js",
      "npm:babel-helper-define-map@6.9.0.js",
      "npm:babel-helper-define-map@6.9.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-classes@6.9.0/lib/loose.js",
      "npm:babel-plugin-transform-es2015-block-scoped-functions@6.8.0.js",
      "npm:babel-plugin-transform-es2015-block-scoped-functions@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-arrow-functions@6.8.0.js",
      "npm:babel-plugin-transform-es2015-arrow-functions@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-function-name@6.9.0.js",
      "npm:babel-plugin-transform-es2015-function-name@6.9.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-literals@6.8.0.js",
      "npm:babel-plugin-transform-es2015-literals@6.8.0/lib/index.js",
      "npm:babel-plugin-transform-es2015-template-literals@6.8.0.js",
      "npm:babel-plugin-transform-es2015-template-literals@6.8.0/lib/index.js",
      "npm:babel-core@5.8.38.js",
      "npm:babel-core@5.8.38/browser.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-polyfill": "npm:babel-polyfill@6.9.1",
    "babel-preset-es2015": "npm:babel-preset-es2015@6.9.0",
    "babel-preset-react": "npm:babel-preset-react@6.11.1",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bluebird": "npm:bluebird@3.4.1",
    "capaj/systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.5.9",
    "classnames": "npm:classnames@2.2.5",
    "core-js": "npm:core-js@1.2.7",
    "es6-enum": "npm:es6-enum@1.0.3",
    "lodash": "npm:lodash@4.13.1",
    "markdown-it": "npm:markdown-it@7.0.0",
    "mobx": "npm:mobx@2.4.1",
    "mobx-react": "npm:mobx-react@3.5.3",
    "mobx-react-devtools": "npm:mobx-react-devtools@4.2.4",
    "moment": "npm:moment@2.14.1",
    "phoenix-socket": "npm:phoenix-socket@1.1.3",
    "prosemirror": "npm:prosemirror@0.9.1",
    "react": "npm:react@0.14.8",
    "react-dom": "npm:react-dom@0.14.8",
    "react-router": "npm:react-router@2.6.1",
    "react-tap-event-plugin": "npm:react-tap-event-plugin@0.2.2",
    "remarkable": "npm:remarkable@1.6.2",
    "whatwg-fetch": "npm:whatwg-fetch@0.11.1",
    "github:capaj/systemjs-hot-reloader@0.5.9": {
      "debug": "npm:debug@2.2.0",
      "socket.io-client": "github:socketio/socket.io-client@1.4.8",
      "weakee": "npm:weakee@1.0.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.7"
    },
    "github:jspm/nodelibs-punycode@0.1.0": {
      "punycode": "npm:punycode@1.4.1"
    },
    "github:jspm/nodelibs-querystring@0.1.0": {
      "querystring": "npm:querystring@0.2.0"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:argparse@0.1.16": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "underscore": "npm:underscore@1.7.0",
      "underscore.string": "npm:underscore.string@2.4.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:argparse@1.0.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "sprintf-js": "npm:sprintf-js@1.0.3",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:asap@2.0.4": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:autolinker@0.15.3": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-code-frame@6.11.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "chalk": "npm:chalk@1.1.3",
      "esutils": "npm:esutils@2.0.2",
      "js-tokens": "npm:js-tokens@2.0.0"
    },
    "npm:babel-core@6.10.4": {
      "babel-code-frame": "npm:babel-code-frame@6.11.0",
      "babel-generator": "npm:babel-generator@6.11.3",
      "babel-helpers": "npm:babel-helpers@6.8.0",
      "babel-messages": "npm:babel-messages@6.8.0",
      "babel-register": "npm:babel-register@6.9.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1",
      "babylon": "npm:babylon@6.8.4",
      "convert-source-map": "npm:convert-source-map@1.2.0",
      "debug": "npm:debug@2.2.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "json5": "npm:json5@0.4.0",
      "lodash": "npm:lodash@4.13.1",
      "minimatch": "npm:minimatch@3.0.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-exists": "npm:path-exists@1.0.0",
      "path-is-absolute": "npm:path-is-absolute@1.0.0",
      "private": "npm:private@0.1.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "shebang-regex": "npm:shebang-regex@1.0.0",
      "slash": "npm:slash@1.0.0",
      "source-map": "npm:source-map@0.5.6",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-generator@6.11.3": {
      "babel-messages": "npm:babel-messages@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "detect-indent": "npm:detect-indent@3.0.1",
      "lodash": "npm:lodash@4.13.1",
      "source-map": "npm:source-map@0.5.6"
    },
    "npm:babel-helper-builder-react-jsx@6.9.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1",
      "esutils": "npm:esutils@2.0.2",
      "lodash": "npm:lodash@4.13.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-helper-call-delegate@6.8.0": {
      "babel-helper-hoist-variables": "npm:babel-helper-hoist-variables@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helper-define-map@6.9.0": {
      "babel-helper-function-name": "npm:babel-helper-function-name@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1",
      "lodash": "npm:lodash@4.13.1"
    },
    "npm:babel-helper-function-name@6.8.0": {
      "babel-helper-get-function-arity": "npm:babel-helper-get-function-arity@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helper-get-function-arity@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helper-hoist-variables@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helper-optimise-call-expression@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helper-regex@6.9.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1",
      "lodash": "npm:lodash@4.13.1"
    },
    "npm:babel-helper-replace-supers@6.8.0": {
      "babel-helper-optimise-call-expression": "npm:babel-helper-optimise-call-expression@6.8.0",
      "babel-messages": "npm:babel-messages@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-helpers@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0"
    },
    "npm:babel-messages@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-plugin-check-es2015-constants@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-syntax-async-functions@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-syntax-flow@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-syntax-jsx@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-arrow-functions@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-block-scoped-functions@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-block-scoping@6.10.1": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1",
      "lodash": "npm:lodash@4.13.1"
    },
    "npm:babel-plugin-transform-es2015-classes@6.9.0": {
      "babel-helper-define-map": "npm:babel-helper-define-map@6.9.0",
      "babel-helper-function-name": "npm:babel-helper-function-name@6.8.0",
      "babel-helper-optimise-call-expression": "npm:babel-helper-optimise-call-expression@6.8.0",
      "babel-helper-replace-supers": "npm:babel-helper-replace-supers@6.8.0",
      "babel-messages": "npm:babel-messages@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-computed-properties@6.8.0": {
      "babel-helper-define-map": "npm:babel-helper-define-map@6.9.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0"
    },
    "npm:babel-plugin-transform-es2015-destructuring@6.9.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-duplicate-keys@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-for-of@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-function-name@6.9.0": {
      "babel-helper-function-name": "npm:babel-helper-function-name@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-literals@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-modules-commonjs@6.10.3": {
      "babel-plugin-transform-strict-mode": "npm:babel-plugin-transform-strict-mode@6.11.3",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-types": "npm:babel-types@6.11.1",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:babel-plugin-transform-es2015-object-super@6.8.0": {
      "babel-helper-replace-supers": "npm:babel-helper-replace-supers@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-parameters@6.11.3": {
      "babel-helper-call-delegate": "npm:babel-helper-call-delegate@6.8.0",
      "babel-helper-get-function-arity": "npm:babel-helper-get-function-arity@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-template": "npm:babel-template@6.9.0",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-shorthand-properties@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-spread@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-sticky-regex@6.8.0": {
      "babel-helper-regex": "npm:babel-helper-regex@6.9.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-plugin-transform-es2015-template-literals@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-typeof-symbol@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-es2015-unicode-regex@6.11.0": {
      "babel-helper-regex": "npm:babel-helper-regex@6.9.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "regexpu-core": "npm:regexpu-core@2.0.0"
    },
    "npm:babel-plugin-transform-flow-strip-types@6.8.0": {
      "babel-plugin-syntax-flow": "npm:babel-plugin-syntax-flow@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-react-display-name@6.8.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:babel-plugin-transform-react-jsx-self@6.11.0": {
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-react-jsx-source@6.9.0": {
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-react-jsx@6.8.0": {
      "babel-helper-builder-react-jsx": "npm:babel-helper-builder-react-jsx@6.9.0",
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2"
    },
    "npm:babel-plugin-transform-regenerator@6.9.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "babel-core": "npm:babel-core@6.10.4",
      "babel-plugin-syntax-async-functions": "npm:babel-plugin-syntax-async-functions@6.8.0",
      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@6.10.1",
      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1",
      "babylon": "npm:babylon@6.8.4",
      "private": "npm:private@0.1.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:babel-plugin-transform-strict-mode@6.11.3": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1"
    },
    "npm:babel-polyfill@6.9.1": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "core-js": "npm:core-js@2.4.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "regenerator-runtime": "npm:regenerator-runtime@0.9.5"
    },
    "npm:babel-preset-es2015@6.9.0": {
      "babel-plugin-check-es2015-constants": "npm:babel-plugin-check-es2015-constants@6.8.0",
      "babel-plugin-transform-es2015-arrow-functions": "npm:babel-plugin-transform-es2015-arrow-functions@6.8.0",
      "babel-plugin-transform-es2015-block-scoped-functions": "npm:babel-plugin-transform-es2015-block-scoped-functions@6.8.0",
      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@6.10.1",
      "babel-plugin-transform-es2015-classes": "npm:babel-plugin-transform-es2015-classes@6.9.0",
      "babel-plugin-transform-es2015-computed-properties": "npm:babel-plugin-transform-es2015-computed-properties@6.8.0",
      "babel-plugin-transform-es2015-destructuring": "npm:babel-plugin-transform-es2015-destructuring@6.9.0",
      "babel-plugin-transform-es2015-duplicate-keys": "npm:babel-plugin-transform-es2015-duplicate-keys@6.8.0",
      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@6.8.0",
      "babel-plugin-transform-es2015-function-name": "npm:babel-plugin-transform-es2015-function-name@6.9.0",
      "babel-plugin-transform-es2015-literals": "npm:babel-plugin-transform-es2015-literals@6.8.0",
      "babel-plugin-transform-es2015-modules-commonjs": "npm:babel-plugin-transform-es2015-modules-commonjs@6.10.3",
      "babel-plugin-transform-es2015-object-super": "npm:babel-plugin-transform-es2015-object-super@6.8.0",
      "babel-plugin-transform-es2015-parameters": "npm:babel-plugin-transform-es2015-parameters@6.11.3",
      "babel-plugin-transform-es2015-shorthand-properties": "npm:babel-plugin-transform-es2015-shorthand-properties@6.8.0",
      "babel-plugin-transform-es2015-spread": "npm:babel-plugin-transform-es2015-spread@6.8.0",
      "babel-plugin-transform-es2015-sticky-regex": "npm:babel-plugin-transform-es2015-sticky-regex@6.8.0",
      "babel-plugin-transform-es2015-template-literals": "npm:babel-plugin-transform-es2015-template-literals@6.8.0",
      "babel-plugin-transform-es2015-typeof-symbol": "npm:babel-plugin-transform-es2015-typeof-symbol@6.8.0",
      "babel-plugin-transform-es2015-unicode-regex": "npm:babel-plugin-transform-es2015-unicode-regex@6.11.0",
      "babel-plugin-transform-regenerator": "npm:babel-plugin-transform-regenerator@6.9.0"
    },
    "npm:babel-preset-react@6.11.1": {
      "babel-plugin-syntax-flow": "npm:babel-plugin-syntax-flow@6.8.0",
      "babel-plugin-syntax-jsx": "npm:babel-plugin-syntax-jsx@6.8.0",
      "babel-plugin-transform-flow-strip-types": "npm:babel-plugin-transform-flow-strip-types@6.8.0",
      "babel-plugin-transform-react-display-name": "npm:babel-plugin-transform-react-display-name@6.8.0",
      "babel-plugin-transform-react-jsx": "npm:babel-plugin-transform-react-jsx@6.8.0",
      "babel-plugin-transform-react-jsx-self": "npm:babel-plugin-transform-react-jsx-self@6.11.0",
      "babel-plugin-transform-react-jsx-source": "npm:babel-plugin-transform-react-jsx-source@6.9.0"
    },
    "npm:babel-register@6.9.0": {
      "babel-core": "npm:babel-core@6.10.4",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "core-js": "npm:core-js@2.4.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "home-or-tmp": "npm:home-or-tmp@1.0.0",
      "lodash": "npm:lodash@4.13.1",
      "mkdirp": "npm:mkdirp@0.5.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-exists": "npm:path-exists@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map-support": "npm:source-map-support@0.2.10"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-runtime@6.9.2": {
      "core-js": "npm:core-js@2.4.1",
      "regenerator-runtime": "npm:regenerator-runtime@0.9.5"
    },
    "npm:babel-template@6.9.0": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "babel-types": "npm:babel-types@6.11.1",
      "babylon": "npm:babylon@6.8.4",
      "lodash": "npm:lodash@4.13.1"
    },
    "npm:babel-traverse@6.10.4": {
      "babel-code-frame": "npm:babel-code-frame@6.11.0",
      "babel-messages": "npm:babel-messages@6.8.0",
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-types": "npm:babel-types@6.11.1",
      "babylon": "npm:babylon@6.8.4",
      "debug": "npm:debug@2.2.0",
      "globals": "npm:globals@8.18.0",
      "invariant": "npm:invariant@2.2.1",
      "lodash": "npm:lodash@4.13.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-types@6.11.1": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "babel-traverse": "npm:babel-traverse@6.10.4",
      "esutils": "npm:esutils@2.0.2",
      "lodash": "npm:lodash@4.13.1",
      "to-fast-properties": "npm:to-fast-properties@1.0.2"
    },
    "npm:babylon@6.8.4": {
      "babel-runtime": "npm:babel-runtime@6.9.2",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bluebird@3.4.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:brace-expansion@1.1.5": {
      "balanced-match": "npm:balanced-match@0.4.1",
      "concat-map": "npm:concat-map@0.0.1"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:chalk@1.1.3": {
      "ansi-styles": "npm:ansi-styles@2.2.1",
      "escape-string-regexp": "npm:escape-string-regexp@1.0.5",
      "has-ansi": "npm:has-ansi@2.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "strip-ansi": "npm:strip-ansi@3.0.1",
      "supports-color": "npm:supports-color@2.0.0"
    },
    "npm:convert-source-map@1.2.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@2.4.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@2.4.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:d@0.1.1": {
      "es5-ext": "npm:es5-ext@0.10.12"
    },
    "npm:debug@2.2.0": {
      "ms": "npm:ms@0.7.1"
    },
    "npm:detect-indent@3.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "get-stdin": "npm:get-stdin@4.0.1",
      "minimist": "npm:minimist@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "repeating": "npm:repeating@1.1.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:entities@1.1.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:es5-ext@0.10.12": {
      "es6-iterator": "npm:es6-iterator@2.0.0",
      "es6-symbol": "npm:es6-symbol@3.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:es6-enum@1.0.3": {
      "es6-symbol": "npm:es6-symbol@3.1.0"
    },
    "npm:es6-iterator@2.0.0": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.12",
      "es6-symbol": "npm:es6-symbol@3.1.0"
    },
    "npm:es6-symbol@3.1.0": {
      "d": "npm:d@0.1.1",
      "es5-ext": "npm:es5-ext@0.10.12"
    },
    "npm:fbjs@0.2.1": {
      "core-js": "npm:core-js@1.2.7",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "whatwg-fetch": "npm:whatwg-fetch@0.9.0"
    },
    "npm:fbjs@0.6.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:get-stdin@4.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:globals@8.18.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:has-ansi@2.0.0": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:history@2.1.2": {
      "deep-equal": "npm:deep-equal@1.0.1",
      "invariant": "npm:invariant@2.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.3",
      "warning": "npm:warning@2.1.0"
    },
    "npm:home-or-tmp@1.0.0": {
      "os-tmpdir": "npm:os-tmpdir@1.0.1",
      "user-home": "npm:user-home@1.1.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.1": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:is-finite@1.0.1": {
      "number-is-nan": "npm:number-is-nan@1.0.0"
    },
    "npm:isarray@1.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:json5@0.4.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:linkify-it@1.2.4": {
      "uc.micro": "npm:uc.micro@1.0.2"
    },
    "npm:linkify-it@2.0.0": {
      "uc.micro": "npm:uc.micro@1.0.2"
    },
    "npm:loose-envify@1.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:markdown-it@6.1.1": {
      "argparse": "npm:argparse@1.0.7",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "entities": "npm:entities@1.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "linkify-it": "npm:linkify-it@1.2.4",
      "mdurl": "npm:mdurl@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "punycode": "github:jspm/nodelibs-punycode@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "uc.micro": "npm:uc.micro@1.0.2"
    },
    "npm:markdown-it@7.0.0": {
      "argparse": "npm:argparse@1.0.7",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "entities": "npm:entities@1.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "linkify-it": "npm:linkify-it@2.0.0",
      "mdurl": "npm:mdurl@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "punycode": "github:jspm/nodelibs-punycode@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "uc.micro": "npm:uc.micro@1.0.2"
    },
    "npm:minimatch@3.0.2": {
      "brace-expansion": "npm:brace-expansion@1.1.5",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:mkdirp@0.5.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "minimist": "npm:minimist@0.0.8",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:mobx-react-devtools@4.2.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "mobx": "npm:mobx@2.4.1",
      "mobx-react": "npm:mobx-react@3.5.3",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:mobx-react@3.5.3": {
      "mobx": "npm:mobx@2.4.1"
    },
    "npm:os-tmpdir@1.0.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-exists@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:path-is-absolute@1.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:phoenix-socket@1.1.3": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.7": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:prosemirror@0.9.1": {
      "browserkeymap": "npm:browserkeymap@1.0.1",
      "markdown-it": "npm:markdown-it@6.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "subscription": "npm:subscription@3.0.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:punycode@1.4.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:query-string@3.0.3": {
      "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
    },
    "npm:react-dom@0.14.8": {
      "react": "npm:react@0.14.8"
    },
    "npm:react-router@2.6.1": {
      "history": "npm:history@2.1.2",
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
      "invariant": "npm:invariant@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.8",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react-tap-event-plugin@0.2.2": {
      "fbjs": "npm:fbjs@0.2.1",
      "react": "npm:react@0.14.8"
    },
    "npm:react@0.14.8": {
      "fbjs": "npm:fbjs@0.6.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:regenerator-runtime@0.9.5": {
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:regexpu-core@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "regenerate": "npm:regenerate@1.3.1",
      "regjsgen": "npm:regjsgen@0.2.0",
      "regjsparser": "npm:regjsparser@0.1.5",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:regjsparser@0.1.5": {
      "jsesc": "npm:jsesc@0.5.0"
    },
    "npm:remarkable@1.6.2": {
      "argparse": "npm:argparse@0.1.16",
      "autolinker": "npm:autolinker@0.15.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:repeating@1.1.3": {
      "is-finite": "npm:is-finite@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:source-map-support@0.2.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "querystring": "github:jspm/nodelibs-querystring@0.1.0",
      "source-map": "npm:source-map@0.1.32"
    },
    "npm:source-map@0.1.32": {
      "amdefine": "npm:amdefine@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map@0.5.6": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:strip-ansi@3.0.1": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:supports-color@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:user-home@1.1.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:warning@3.0.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
